config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :index
  resources :users, :only => [:index, :show, :destroy]
  root controller: :index, action: :index
 
get '/register', to: 'users#new' 
post '/register', to: 'users#create' 

 
  get    '/login',   to: 'sessions#new'   
  post   '/login',   to: 'sessions#create'   
  delete '/logout',  to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id         :bigint           not null, primary key
#  deleted_at :datetime
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#
class Course < ApplicationRecord
    
end

app/models/subject.rb
# == Schema Information
#
# Table name: subjects
#
#  id         :bigint           not null, primary key
#  deleted_at :datetime
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#
class Subject < ApplicationRecord
    
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                   :bigint           not null, primary key
#  address              :string
#  avatar_url           :string
#  birthday             :datetime
#  confirmation_sent_at :datetime
#  confirmation_token   :string
#  confirmed_at         :datetime
#  deleted_at           :datetime
#  email                :string           not null
#  fullname             :string
#  password_digest      :string           not null
#  role                 :integer          default(1), not null
#  created_at           :datetime
#  updated_at           :datetime
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
    has_secure_password

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include SessionsHelper
	def logged_in_user
        unless logged_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to login_url
        end
      end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
       
        def log_in(user)
         session[:user_id] = user.id
        end

        def destroy
         log_out if logged_in?
         redirect_to root_url
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        
    end

    def new
         @user= User.new
    end

    def create 
	binding.pry
   	@user= User.create(params_permit)
	if @user.save!
           log_in @user 
           flash[:success] = "Welcome to #{@user.fullname}"
           redirect_to @user
	else
	   render 'new'
	end

    end

    def params_permit
        params.require(:user).permit(
          :fullname,
          :email,
          :password_digest
        )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
        session[:user_id] = user.id
    end

    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def current_user?(user)
        user == current_user
    end

    def current_user
        if(user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            raise
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end
    
   
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/index.html.erb
<!-- header END ==== -->
<!-- Content -->
<div class="page-content bg-white">
   <!-- inner page banner -->
   <div class="page-banner ovbl-dark" style="background-image:url(assets/images/banner/banner3.jpg);">
      <div class="container">
         <div class="page-banner-entry">
            <h1 class="text-white">Our Courses</h1>
         </div>
      </div>
   </div>
   <!-- Breadcrumb row -->
   <div class="breadcrumb-row">
      <div class="container">
         <ul class="list-inline">
            <li><a href="#">Home</a></li>
            <li>Our Courses</li>
         </ul>
      </div>
   </div>
   <!-- Breadcrumb row END -->
   <!-- inner page banner END -->
   <div class="content-block">
      <!-- About Us -->
      <div class="section-area section-sp1">
         <div class="container">
            <div class="row">
               <div class="col-lg-3 col-md-4 col-sm-12 m-b30">
                  <div class="widget courses-search-bx placeani">
                     <div class="form-group">
                        <div class="input-group">
                           <label>Search Courses</label>
                           <input name="dzName" type="text" required class="form-control">
                        </div>
                     </div>
                  </div>
                  <div class="widget widget_archive">
                     <h5 class="widget-title style-1">All Courses</h5>
                     <ul>
                        <li class="active"><a href="#">General</a></li>
                        <li><a href="#">IT & Software</a></li>
                        <li><a href="#">Photography</a></li>
                        <li><a href="#">Programming Language</a></li>
                        <li><a href="#">Technology</a></li>
                     </ul>
                  </div>
                  <div class="widget">
                     <a href="#">
                     <%=image_tag("blog/recent-blog/pic1.jpg")%> 
                     </a>
                  </div>
                  <div class="widget recent-posts-entry widget-courses">
                     <h5 class="widget-title style-1">Recent Courses</h5>
                     <div class="widget-post-bx">
                        <div class="widget-post clearfix">
                           <div class="ttr-post-media"> 
                              <%=image_tag("blog/recent-blog/pic1.jpg")%> 
                           </div>
                           <div class="ttr-post-info">
                              <div class="ttr-post-header">
                                 <h6 class="post-title"><a href="#">Introduction EduChamp</a></h6>
                              </div>
                              <div class="ttr-post-meta">
                                 <ul>
                                    <li class="price">
                                       <del>$190</del>
                                       <h5>$120</h5>
                                    </li>
                                    <li class="review">03 Review</li>
                                 </ul>
                              </div>
                           </div>
                        </div>
                        <div class="widget-post clearfix">
                           <div class="ttr-post-media"> 
                              <%=image_tag("blog/recent-blog/pic3.jpg")%> 
                           </div>
                           <div class="ttr-post-info">
                              <div class="ttr-post-header">
                                 <h6 class="post-title"><a href="#">English For Tommorow</a></h6>
                              </div>
                              <div class="ttr-post-meta">
                                 <ul>
                                    <li class="price">
                                       <h5 class="free">Free</h5>
                                    </li>
                                    <li class="review">07 Review</li>
                                 </ul>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="col-lg-9 col-md-8 col-sm-12">
                  <div class="row">
                     <div class="col-md-6 col-lg-4 col-sm-6 m-b30">
                        <div class="cours-bx">
                           <div class="action-box">
                              <%=image_tag("courses/pic1.jpg")%> 
                              <a href="#" class="btn">Read More</a>
                           </div>
                           <div class="info-bx text-center">
                              <h5><a href="#">Introduction EduChamp – LMS plugin</a></h5>
                              <span>Programming</span>
                           </div>
                           <div class="cours-more-info">
                              <div class="review">
                                 <span>3 Review</span>
                                 <ul class="cours-star">
                                    <li class="active"><i class="fa fa-star"></i></li>
                                    <li class="active"><i class="fa fa-star"></i></li>
                                    <li class="active"><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                 </ul>
                              </div>
                              <div class="price">
                                 <del>$190</del>
                                 <h5>$120</h5>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-lg-12 m-b20">
                        <div class="pagination-bx rounded-sm gray clearfix">
                           <ul class="pagination">
                              <li class="previous"><a href="#"><i class="ti-arrow-left"></i> Prev</a></li>
                              <li class="active"><a href="#">1</a></li>
                              <li><a href="#">2</a></li>
                              <li><a href="#">3</a></li>
                              <li class="next"><a href="#">Next <i class="ti-arrow-right"></i></a></li>
                           </ul>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- contact area END -->
</div>

app/views/layouts/_footer.html.erb
<footer>
   <div class="footer-top">
      <div class="pt-exebar">
         <div class="container">
            <div class="d-flex align-items-stretch">
               <div class="pt-logo mr-auto">
                  <%=image_tag("logo-white.png")%> 
               </div>
               <div class="pt-social-link">
                  <ul class="list-inline m-a0">
                     <li><a href="#" class="btn-link"><i class="fa fa-facebook"></i></a></li>
                     <li><a href="#" class="btn-link"><i class="fa fa-twitter"></i></a></li>
                     <li><a href="#" class="btn-link"><i class="fa fa-linkedin"></i></a></li>
                     <li><a href="#" class="btn-link"><i class="fa fa-google-plus"></i></a></li>
                  </ul>
               </div>
               <div class="pt-btn-join">
                  <a href="#" class="btn ">Join Now</a>
               </div>
            </div>
         </div>
      </div>
      <div class="container">
         <div class="row">
            <div class="col-lg-4 col-md-12 col-sm-12 footer-col-4">
               <div class="widget">
                  <h5 class="footer-title">Sign Up For A Newsletter</h5>
                  <p class="text-capitalize m-b20">Weekly Breaking news analysis and cutting edge advices on job searching.</p>
                  <div class="subscribe-form m-b20">
                     <form class="subscription-form" action="http://educhamp.themetrades.com/demo/assets/script/mailchamp.php" method="post">
                        <div class="ajax-message"></div>
                        <div class="input-group">
                           <input name="email" required="required"  class="form-control" placeholder="Your Email Address" type="email">
                           <span class="input-group-btn">
                           <button name="submit" value="Submit" type="submit" class="btn"><i class="fa fa-arrow-right"></i></button>
                           </span> 
                        </div>
                     </form>
                  </div>
               </div>
            </div>
            <div class="col-12 col-lg-5 col-md-7 col-sm-12">
               <div class="row">
                  <div class="col-4 col-lg-4 col-md-4 col-sm-4">
                     <div class="widget footer_widget">
                        <h5 class="footer-title">Company</h5>
                        <ul>
                           <li><a href="index.html">Home</a></li>
                           <li><a href="about-1.html">About</a></li>
                           <li><a href="faq-1.html">FAQs</a></li>
                           <li><a href="contact-1.html">Contact</a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-4 col-lg-4 col-md-4 col-sm-4">
                     <div class="widget footer_widget">
                        <h5 class="footer-title">Get In Touch</h5>
                        <ul>
                           <li><a href="http://educhamp.themetrades.com/admin/index.html">Dashboard</a></li>
                           <li><a href="blog-classic-grid.html">Blog</a></li>
                           <li><a href="portfolio.html">Portfolio</a></li>
                           <li><a href="event.html">Event</a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-4 col-lg-4 col-md-4 col-sm-4">
                     <div class="widget footer_widget">
                        <h5 class="footer-title">Courses</h5>
                        <ul>
                           <li><a href="courses.html">Courses</a></li>
                           <li><a href="courses-details.html">Details</a></li>
                           <li><a href="membership.html">Membership</a></li>
                           <li><a href="profile.html">Profile</a></li>
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
            <div class="col-12 col-lg-3 col-md-5 col-sm-12 footer-col-4">
               <div class="widget widget_gallery gallery-grid-4">
                  <h5 class="footer-title">Our Gallery</h5>
                  <ul class="magnific-image">
                     <li><a href="assets/images/gallery/pic1.jpg" class="magnific-anchor"><%=image_tag("gallery/pic1.jpg")%>  </a></li>
                     <li><a href="assets/images/gallery/pic2.jpg" class="magnific-anchor"><%=image_tag("gallery/pic2.jpg")%> </a></li>
                     <li><a href="assets/images/gallery/pic3.jpg" class="magnific-anchor"><%=image_tag("gallery/pic3.jpg")%></a></li>
                     <li><a href="assets/images/gallery/pic4.jpg" class="magnific-anchor"><%=image_tag("gallery/pic4.jpg")%></a></li>
                     <li><a href="assets/images/gallery/pic5.jpg" class="magnific-anchor"><%=image_tag("gallery/pic5.jpg")%></a></li>
                     <li><a href="assets/images/gallery/pic6.jpg" class="magnific-anchor"><%=image_tag("gallery/pic6.jpg")%></a></li>
                     <li><a href="assets/images/gallery/pic7.jpg" class="magnific-anchor"><%=image_tag("gallery/pic7.jpg")%></a></li>
                     <li><a href="assets/images/gallery/pic8.jpg" class="magnific-anchor"><%=image_tag("gallery/pic8.jpg")%></a></li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
   </div>
   <div class="footer-bottom">
      <div class="container">
         <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 text-center"> <a target="_blank" href="https://www.templateshub.net">Templates Hub</a></div>
         </div>
      </div>
   </div>
</footer>

app/views/layouts/_menu.html.erb
<div class="top-bar">
   <div class="container">
      <div class="row d-flex justify-content-between">
         <div class="topbar-left">
            <ul>
               <li><a href="faq-1.html"><i class="fa fa-question-circle"></i>Ask a Question</a></li>
               <li><a href="javascript:;"><i class="fa fa-envelope-o"></i>Support@website.com</a></li>
            </ul>
         </div>
         <div class="topbar-right">
            <ul>
               <li>
                  <select class="header-lang-bx">
                     <option data-icon="flag flag-uk">English UK</option>
                     <option data-icon="flag flag-us">English US</option>
                  </select>
               </li>
               <% if logged_in? %>
               <%= link_to "Log out", logout_path, method: :delete %>
               <% else %>
               <li><%= link_to "Login", login_path %></li>
               <li><%= link_to "Register", register_path %></li>
               <% end %>
            </ul>
         </div>
      </div>
   </div>
</div>
<div class="sticky-header navbar-expand-lg">
   <div class="menu-bar clearfix">
      <div class="container clearfix">
         <!-- Header Logo ==== -->
         <div class="menu-logo">
            <%=image_tag("logo.png")%> 
            </a>
         </div>
         <!-- Mobile Nav Button ==== -->
         <button class="navbar-toggler collapsed menuicon justify-content-end" type="button" data-toggle="collapse" data-target="#menuDropdown" aria-controls="menuDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span></span>
         <span></span>
         <span></span>
         </button>
         <!-- Author Nav ==== -->
         <div class="secondary-menu">
            <div class="secondary-inner">
               <ul>
                  <li><a href="javascript:;" class="btn-link"><i class="fa fa-facebook"></i></a></li>
                  <li><a href="javascript:;" class="btn-link"><i class="fa fa-google-plus"></i></a></li>
                  <li><a href="javascript:;" class="btn-link"><i class="fa fa-linkedin"></i></a></li>
                  <!-- Search Button ==== -->
                  <li class="search-btn"><button id="quik-search-btn" type="button" class="btn-link"><i class="fa fa-search"></i></button></li>
               </ul>
            </div>
         </div>
         <!-- Search Box ==== -->
         <div class="nav-search-bar">
            <form action="#">
               <input name="search" value="" type="text" class="form-control" placeholder="Type to search">
               <span><i class="ti-search"></i></span>
            </form>
            <span id="search-remove"><i class="ti-close"></i></span>
         </div>
         <!-- Navigation Menu ==== -->
         <div class="menu-links navbar-collapse collapse justify-content-start" id="menuDropdown">
            <div class="menu-logo">
               <a href="index.html">
               <%=image_tag("logo.png")%> 
               </a>
            </div>
            <ul class="nav navbar-nav">
               <li class="active">
                  <a href="javascript:;">Home <i class="fa fa-chevron-down"></i></a>
                  <ul class="sub-menu">
                     <li><a href="index.html">Home 1</a></li>
                     <li><a href="index-2.html">Home 2</a></li>
                  </ul>
               </li>
               <li>
                  <a href="javascript:;">Pages <i class="fa fa-chevron-down"></i></a>
                  <ul class="sub-menu">
                     <li>
                        <a href="javascript:;">About<i class="fa fa-angle-right"></i></a>
                        <ul class="sub-menu">
                           <li><a href="about-1.html">About 1</a></li>
                           <li><a href="about-2.html">About 2</a></li>
                        </ul>
                     </li>
                     <li>
                        <a href="javascript:;">Event<i class="fa fa-angle-right"></i></a>
                        <ul class="sub-menu">
                           <li><a href="event.html">Event</a></li>
                           <li><a href="events-details.html">Events Details</a></li>
                        </ul>
                     </li>
                     <li>
                        <a href="javascript:;">FAQ's<i class="fa fa-angle-right"></i></a>
                        <ul class="sub-menu">
                           <li><a href="faq-1.html">FAQ's 1</a></li>
                           <li><a href="faq-2.html">FAQ's 2</a></li>
                        </ul>
                     </li>
                     <li>
                        <a href="javascript:;">Contact Us<i class="fa fa-angle-right"></i></a>
                        <ul class="sub-menu">
                           <li><a href="contact-1.html">Contact Us 1</a></li>
                           <li><a href="contact-2.html">Contact Us 2</a></li>
                        </ul>
                     </li>
                     <li><a href="portfolio.html">Portfolio</a></li>
                     <li><a href="profile.html">Profile</a></li>
                     <li><a href="membership.html">Membership</a></li>
                     <li><a href="error-404.html">404 Page</a></li>
                  </ul>
               </li>
               <li class="add-mega-menu">
                  <a href="javascript:;">Our Courses <i class="fa fa-chevron-down"></i></a>
                  <ul class="sub-menu add-menu">
                     <li class="add-menu-left">
                        <h5 class="menu-adv-title">Our Courses</h5>
                        <ul>
                           <li><a href="courses.html">Courses </a></li>
                           <li><a href="courses-details.html">Courses Details</a></li>
                           <li><a href="profile.html">Instructor Profile</a></li>
                           <li><a href="event.html">Upcoming Event</a></li>
                           <li><a href="membership.html">Membership</a></li>
                        </ul>
                     </li>
                     <li class="add-menu-right">
                        <img src="assets/images/adv/adv.jpg" alt=""/>
                     </li>
                  </ul>
               </li>
               <li>
                  <a href="javascript:;">Blog <i class="fa fa-chevron-down"></i></a>
                  <ul class="sub-menu">
                     <li><a href="blog-classic-grid.html">Blog Classic</a></li>
                     <li><a href="blog-classic-sidebar.html">Blog Classic Sidebar</a></li>
                     <li><a href="blog-list-sidebar.html">Blog List Sidebar</a></li>
                     <li><a href="blog-standard-sidebar.html">Blog Standard Sidebar</a></li>
                     <li><a href="blog-details.html">Blog Details</a></li>
                  </ul>
               </li>
               <li class="nav-dashboard">
                  <a href="javascript:;">Dashboard <i class="fa fa-chevron-down"></i></a>
                  <ul class="sub-menu">
                     <li><a href="admin/index.html">Dashboard</a></li>
                     <li><a href="admin/add-listing.html">Add Listing</a></li>
                     <li><a href="admin/bookmark.html">Bookmark</a></li>
                     <li><a href="admin/courses.html">Courses</a></li>
                     <li><a href="admin/review.html">Review</a></li>
                     <li><a href="admin/teacher-profile.html">Teacher Profile</a></li>
                     <li><a href="admin/user-profile.html">User Profile</a></li>
                     <li>
                        <a href="javascript:;">Calendar<i class="fa fa-angle-right"></i></a>
                        <ul class="sub-menu">
                           <li><a href="admin/basic-calendar.html">Basic Calendar</a></li>
                           <li><a href="admin/list-view-calendar.html">List View Calendar</a></li>
                        </ul>
                     </li>
                     <li>
                        <a href="javascript:;">Mailbox<i class="fa fa-angle-right"></i></a>
                        <ul class="sub-menu">
                           <li><a href="admin/mailbox.html">Mailbox</a></li>
                           <li><a href="admin/mailbox-compose.html">Compose</a></li>
                           <li><a href="admin/mailbox-read.html">Mail Read</a></li>
                        </ul>
                     </li>
                  </ul>
               </li>
            </ul>
            <div class="nav-social-link">
               <a href="javascript:;"><i class="fa fa-facebook"></i></a>
               <a href="javascript:;"><i class="fa fa-google-plus"></i></a>
               <a href="javascript:;"><i class="fa fa-linkedin"></i></a>
            </div>
         </div>
         <!-- Navigation Menu END ==== -->
      </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head class="header rs-nav">
      <title>ELearningV1</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= stylesheet_link_tag @locale_style unless @locale_style.nil? %>
      <%= csrf_meta_tags %>
      <% case request.env['REQUEST_PATH'] %>
      <% when "/register" %>
      <div></div>
      <% when "/login" %>
      <div></div>
      <% else %>
      <%= render 'layouts/menu'%>
      <% end %>
   </head>
   <body>
      <%= yield %>
      <% case request.env['REQUEST_PATH'] %>
      <% when "/register" %>
      <div></div>
      <% when "/login" %>
      <div></div>
      <% else %>
      <%= render 'layouts/footer'%>
      <% end %>
   </body>
</html>

app/views/users/new.html.erb
<div class="page-wraper">
   <div class="account-form">
      <div class="account-head" style="background-image:url(assets/images/background/bg2.jpg);">
         <a href="index.html"><img src="assets/images/logo-white-2.png" alt=""></a>
      </div>
      <div class="account-form-inner">
         <div class="account-container">
            <div class="heading-bx left">
               <h2 class="title-head">Sign Up <span>Now</span></h2>
               <p>Login Your Account <a href="login.html">Click here</a></p>
            </div>
            <%= form_with(url: "/register",class: "contact-bx" ,method: "post") do %>
            <div class="row placeani">
               <div class="col-lg-12">
                  <div class="form-group">
                     <div class="input-group">
                        <label>Your Name</label>
                        <input name="user[fullname]" type="text" required="" class="form-control">
                     </div>
                  </div>
               </div>
               <div class="col-lg-12">
                  <div class="form-group">
                     <div class="input-group">
                        <label>Your Email Address</label>
                        <input name="user[email]" type="email" required="" class="form-control">
                     </div>
                  </div>
               </div>
               <div class="col-lg-12">
                  <div class="form-group">
                     <div class="input-group"> 
                        <label>Your Password</label>
                        <input name="user[password_digest]" type="password" class="form-control" required="">
                     </div>
                  </div>
               </div>
               <div class="col-lg-12 m-b30">
                  <button name="submit" type="submit" value="Submit" class="btn button-md">Sign Up</button>
               </div>
               <div class="col-lg-12">
                  <h6>Sign Up with Social media</h6>
                  <div class="d-flex">
                     <a class="btn flex-fill m-r5 facebook" href="#"><i class="fa fa-facebook"></i>Facebook</a>
                     <a class="btn flex-fill m-l5 google-plus" href="#"><i class="fa fa-google-plus"></i>Google Plus</a>
                  </div>
               </div>
            </div>
            <% end %>
         </div>
      </div>
   </div>
</div>